name: Action Warp Generator

on: 
  workflow_dispatch: # Allows manual run

jobs:
  run-warp-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install httpx

      - name: Run Python script
        env:
          WARP_ID: ${{ secrets.ID }}
          LIMIT: ${{ secrets.LIMIT }}
        run: python warp.py
        
